"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, Union

co = ...
class TavilyHybridClient:
    def __init__(self, api_key: Union[str, None], db_provider: Literal['mongodb'], collection, index: str, embeddings_field: str = ..., content_field: str = ..., embedding_function: Optional[callable] = ..., ranking_function: Optional[callable] = ...) -> None:
        '''
        A client for performing hybrid RAG using both the Tavily API and a local database collection.
        
        Parameters:
        api_key (str): The Tavily API key. If this is set to None, it will be loaded from the environment variable TAVILY_API_KEY.
        db_provider (str): The database provider. Currently only 'mongodb' is supported.
        collection (str): The name of the collection in the database that will be used for local search.
        index (str): The name of the collection's vector search index.
        embeddings_field (str): The name of the field in the collection that contains the embeddings.
        content_field (str): The name of the field in the collection that contains the content.
        embedding_function (callable): If provided, this function will be used to generate embeddings for the search query and documents.
        ranking_function (callable): If provided, this function will be used to rerank the combined results.
        '''
        ...
    
    def search(self, query, max_results=..., max_local=..., max_foreign=..., save_foreign=..., **kwargs) -> list[Any]:
        '''
        Return results for the given query from both the tavily API (foreign) and
        the specified mongo collection (local).
        
        Parameters:
        query (str): The query to search for.
        max_results (int): The maximum number of results to return.
        max_local (int): The maximum number of local results to return.
        max_foreign (int): The maximum number of foreign results to return.
        save_foreign (bool or function): Whether to save the foreign results in the collection.
            If a function is provided, it will be used to transform the foreign results before saving.
        '''
        ...
    


