"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, Sequence, Union

class AsyncTavilyClient:
    """
    Async Tavily API client class.
    """
    def __init__(self, api_key: Optional[str] = ..., company_info_tags: Sequence[str] = ..., proxies: Optional[dict[str, str]] = ..., api_base_url: Optional[str] = ...) -> None:
        ...
    
    async def search(self, query: str, search_depth: Literal["basic", "advanced"] = ..., topic: Literal["general", "news", "finance"] = ..., time_range: Literal["day", "week", "month", "year"] = ..., start_date: str = ..., end_date: str = ..., days: int = ..., max_results: int = ..., include_domains: Sequence[str] = ..., exclude_domains: Sequence[str] = ..., include_answer: Union[bool, Literal["basic", "advanced"]] = ..., include_raw_content: Union[bool, Literal["markdown", "text"]] = ..., include_images: bool = ..., timeout: float = ..., country: str = ..., auto_parameters: bool = ..., include_favicon: bool = ..., **kwargs) -> dict:
        """
        Combined search method. Set search_depth to either "basic" or "advanced".
        """
        ...
    
    async def extract(self, urls: Union[List[str], str], include_images: bool = ..., extract_depth: Literal["basic", "advanced"] = ..., format: Literal["markdown", "text"] = ..., timeout: float = ..., include_favicon: bool = ..., **kwargs) -> dict:
        """
        Combined extract method.
        include_favicon: If True, include the favicon in the extraction results.
        """
        ...
    
    async def crawl(self, url: str, max_depth: int = ..., max_breadth: int = ..., limit: int = ..., instructions: str = ..., select_paths: Sequence[str] = ..., select_domains: Sequence[str] = ..., exclude_paths: Sequence[str] = ..., exclude_domains: Sequence[str] = ..., allow_external: bool = ..., extract_depth: Literal["basic", "advanced"] = ..., include_images: bool = ..., format: Literal["markdown", "text"] = ..., timeout: float = ..., include_favicon: bool = ..., **kwargs) -> dict:
        """
        Combined crawl method.
        
        """
        ...
    
    async def map(self, url: str, max_depth: int = ..., max_breadth: int = ..., limit: int = ..., instructions: str = ..., select_paths: Sequence[str] = ..., select_domains: Sequence[str] = ..., exclude_paths: Sequence[str] = ..., exclude_domains: Sequence[str] = ..., allow_external: bool = ..., include_images: bool = ..., timeout: float = ..., **kwargs) -> dict:
        """
        Combined map method.

        """
        ...
    
    async def get_search_context(self, query: str, search_depth: Literal["basic", "advanced"] = ..., topic: Literal["general", "news", "finance"] = ..., days: int = ..., max_results: int = ..., include_domains: Sequence[str] = ..., exclude_domains: Sequence[str] = ..., max_tokens: int = ..., timeout: float = ..., country: str = ..., include_favicon: bool = ..., **kwargs) -> str:
        """
        Get the search context for a query. Useful for getting only related content from retrieved websites
        without having to deal with context extraction and limitation yourself.

        max_tokens: The maximum number of tokens to return (based on openai token compute). Defaults to 4000.

        Returns a string of JSON containing the search context up to context limit.
        """
        ...
    
    async def qna_search(self, query: str, search_depth: Literal["basic", "advanced"] = ..., topic: Literal["general", "news", "finance"] = ..., days: int = ..., max_results: int = ..., include_domains: Sequence[str] = ..., exclude_domains: Sequence[str] = ..., timeout: float = ..., country: str = ..., include_favicon: bool = ..., **kwargs) -> str:
        """
        Q&A search method. Search depth is advanced by default to get the best answer.
        """
        ...
    
    async def get_company_info(self, query: str, search_depth: Literal["basic", "advanced"] = ..., max_results: int = ..., timeout: float = ..., country: str = ...) -> Sequence[dict]:
        """ Company information search method. Search depth is advanced by default to get the best answer. """
        ...
    


