"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional
from .exceptions import *

class AsyncTavilyClient:
    def __init__(self, api_key: Optional[str] = ..., base_url: str = ..., timeout: int = ...) -> None:
        ...
    
    async def search(self, query: str, search_depth: str = ..., max_results: int = ..., include_domains: Optional[List[str]] = ..., exclude_domains: Optional[List[str]] = ..., include_answer: bool = ..., include_raw_content: bool = ..., **kwargs) -> Dict[str, Any]:
        ...
    
    async def extract(self, urls: List[str], include_images: bool = ..., format: str = ..., **kwargs) -> Dict[str, Any]:
        ...
    
    async def qna_search(self, query: str, search_depth: str = ..., max_results: int = ..., **kwargs) -> str:
        ...
    


