"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional
from .exceptions import *

class TavilyClient:
    def __init__(self, api_key: Optional[str] = ..., base_url: str = ..., timeout: int = ...) -> None:
        """
        Initialize Tavily API client

        Args:
            api_key: Tavily API key. If not provided, will look for TAVILY_API_KEY environment variable
            base_url: Base URL for Tavily API
            timeout: Request timeout in seconds (max 120)
        """
        ...
    
    def get_usage_statistics(self) -> Dict[str, Any]:
        """
        Get current usage statistics for this client instance

        Returns:
            Dictionary containing usage statistics
        """
        ...
    
    def search(self, query: str, search_depth: str = ..., max_results: int = ..., include_domains: Optional[List[str]] = ..., exclude_domains: Optional[List[str]] = ..., include_answer: bool = ..., include_raw_content: bool = ..., **kwargs) -> Dict[str, Any]:
        """
        Perform a web search using Tavily API

        Args:
            query: Search query string
            search_depth: Search depth level ("basic" or "advanced")
            max_results: Maximum number of results to return
            include_domains: List of domains to include in search
            exclude_domains: List of domains to exclude from search
            include_answer: Whether to include AI-generated answer
            include_raw_content: Whether to include raw content
            **kwargs: Additional parameters to pass to API

        Returns:
            Dictionary containing search results
        """
        ...
    
    def extract(self, urls: List[str], include_images: bool = ..., format: str = ..., **kwargs) -> Dict[str, Any]:
        """
        Extract content from URLs using Tavily API

        Args:
            urls: List of URLs to extract content from
            include_images: Whether to include images in extraction
            format: Output format ("markdown", "html", or "text")
            **kwargs: Additional parameters to pass to API

        Returns:
            Dictionary containing extracted content
        """
        ...
    
    def qna_search(self, query: str, search_depth: str = ..., max_results: int = ..., **kwargs) -> str:
        """
        Perform a Q&A style search and return only the answer

        Args:
            query: Question to search for
            search_depth: Search depth level
            max_results: Maximum number of results
            **kwargs: Additional parameters

        Returns:
            AI-generated answer string
        """
        ...
    
    def batch_search(self, queries: List[str], search_depth: str = ..., max_results: int = ..., delay_between_requests: float = ..., **kwargs) -> List[Dict[str, Any]]:
        """
        Perform multiple searches in sequence with optional delay

        Args:
            queries: List of search queries
            search_depth: Search depth level for all queries
            max_results: Maximum results per query
            delay_between_requests: Delay in seconds between requests
            **kwargs: Additional parameters for all searches

        Returns:
            List of search results for each query
        """
        ...
    
    def validate_api_key(self) -> bool:
        """
        Validate the API key by making a simple search request

        Returns:
            Boolean indicating if API key is valid
        """
        ...
    
    def get_search_suggestions(self, query: str, max_suggestions: int = ...) -> List[str]:
        """
        Generate search query suggestions based on input query

        Args:
            query: Initial query string
            max_suggestions: Maximum number of suggestions to return

        Returns:
            List of suggested search queries
        """
        ...
    
    def __repr__(self) -> str:
        """String representation of TavilyClient instance"""
        ...
    
    def __str__(self) -> str:
        """User-friendly string representation"""
        ...
    


