"""
This type stub file was generated by pyright.
"""

class UsageLimitExceededError(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class BadRequestError(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class ForbiddenError(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class InvalidAPIKeyError(Exception):
    def __init__(self, message: str) -> None:
        ...
    


class TimeoutError(Exception):
    def __init__(self, timeout: float) -> None:
        ...
    


class MissingAPIKeyError(Exception):
    def __init__(self) -> None:
        ...
    


