"""
This type stub file was generated by pyright.
"""

class TavilyError(Exception):
    """Base exception for Tavily client"""
    ...


class MissingAPIKeyError(TavilyError):
    """Raised when API key is missing"""
    ...


class InvalidAPIKeyError(TavilyError):
    """Raised when API key is invalid"""
    ...


class UsageLimitExceededError(TavilyError):
    """Raised when usage limit is exceeded"""
    ...


class BadRequestError(TavilyError):
    """Raised for bad requests"""
    ...


class ForbiddenError(TavilyError):
    """Raised for forbidden access"""
    ...


class TimeoutError(TavilyError):
    """Raised when request times out"""
    ...


