"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Sequence

def get_total_tokens_from_string(string: str, encoding_name: str = ...) -> int:
    """
        Get total amount of tokens from string using the specified encoding (based on openai compute)
    """
    ...

def get_max_tokens_from_string(string: str, max_tokens: int, encoding_name: str = ...) -> str:
    """
        Extract max tokens from string using the specified encoding (based on openai compute)
    """
    ...

def get_max_items_from_list(data: Sequence[dict], max_tokens: int = ...) -> List[Dict[str, str]]:
    """
        Get max items from list of items based on defined max tokens (based on openai compute)
    """
    ...

